management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /

logging:
  level:
    org.tbaCase: info

server:
  servlet:
    contextPath: /cranes
  error:
    whitelabel:
      enabled: false
  port: 8080
